---
title: "Weight of Fish"
author: "Tracy Alset"
date: "06/30/22"  
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5

 
    
---


```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
```

```{r}
fish<-read.csv(file="Fish.csv")

```


# Predicting Fish Weight


## Perch
```{r}
Perch<-filter(fish, Species=="Perch")
Perch<- select(Perch, -Species )
```

### Best Models

```{r}
library(leaps)
regsubsets.out <-
    regsubsets(Weight ~ .,
               data = Perch,
               nbest = 1,       # 1 best model for each number of predictors
               nvmax = NULL,    # NULL for no limit on number of variables
               force.in = NULL, force.out = NULL,
               method = "exhaustive")

summary.out <- summary(regsubsets.out)
as.data.frame(summary.out$outmat)
library(car)
subsets(regsubsets.out,statistic="adjr2",legend="bottomright",main="Adjusted R^2")
```
### Best Two regressor model

 The best regression model is the one with the highest adjusted r squared value and that is Height and Width and it has 2 regressors , so it is the model we're looking for.

### Smelt
```{r}
Smelt<-filter(fish, Species=="Smelt")
Smelt<- select(Smelt, -Species )
```

### Best models:

```{r}
library(leaps)
regsubsets.out <-
    regsubsets(Weight ~ .,
               data = Smelt,
               nbest = 1,       # 1 best model for each number of predictors
               nvmax = NULL,    # NULL for no limit on number of variables
               force.in = NULL, force.out = NULL,
               method = "exhaustive")

summary.out <- summary(regsubsets.out)
as.data.frame(summary.out$outmat)
library(car)
subsets(regsubsets.out,statistic="adjr2",legend="bottomright",main="Adjusted R^2")
```






## Pike

### Best Models

### Best Two regressor model

## Roach

### Best Models

### Best Two regressor model

## Final Summary Statements